// generated by stringer -type=OpType op.go token.go; DO NOT EDIT

package ast

import "fmt"

const _OpType_name = "OpNoneOpAddOpSubOpDivOpMulOpPowOpConcat"

var _OpType_index = [...]uint8{0, 6, 11, 16, 21, 26, 31, 39}

func (i OpType) String() string {
	if i < 0 || i+1 >= OpType(len(_OpType_index)) {
		return fmt.Sprintf("OpType(%d)", i)
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
