// generated by stringer -type=UnitType token.go unit.go; DO NOT EDIT

package ast

import "fmt"

const _UnitType_name = "UNIT_NONEUNIT_EMUNIT_EXUNIT_CHUNIT_REMUNIT_CMUNIT_INUNIT_MMUNIT_PCUNIT_PTUNIT_PXUNIT_VHUNIT_VWUNIT_VMINUNIT_VMAXUNIT_DEGUNIT_GRADUNIT_RADUNIT_TURNUNIT_PERCENTUNIT_SECONDUNIT_MILLISECONDUNIT_DPIUNIT_DPPXUNIT_DPCM"

var _UnitType_index = [...]uint8{0, 9, 16, 23, 30, 38, 45, 52, 59, 66, 73, 80, 87, 94, 103, 112, 120, 129, 137, 146, 158, 169, 185, 193, 202, 211}

func (i UnitType) String() string {
	if i < 0 || i+1 >= UnitType(len(_UnitType_index)) {
		return fmt.Sprintf("UnitType(%d)", i)
	}
	return _UnitType_name[_UnitType_index[i]:_UnitType_index[i+1]]
}
