---
# travis and modern c++ http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language: cpp
git:
  depth: 1
addons:
  apt:
    packages:
    # - gcc-5
    # - g++-5
    # - clang-3.6
    # - libgflags-dev
compiler:
- clang
- gcc
install:
- wget 'https://googletest.googlecode.com/files/gtest-1.7.0.zip'
- unzip gtest-1.7.0.zip
- ln -s gtest-1.7.0 gtest
script:
- cmake .

# after_success:
# - goveralls -coverprofile=c6.cov -service=travis-ci
# notifications:
#  slack:
#    secure: Af6bRpbwtC4794UtB1phbubk63KdethyuMFkk9bxTrEwzTgMN4AdLLv4DYjoeETBhPw3FKc6LurzhsRfNnNT14FaZAW3ZmMTUPxHNKnxu9EvloaizXpwxkKgeVNHneA8gytXZ+s/r/rgP/IkSJcbvbLfpkNvT+lNyPW32jK0CW8=
