language: go
before_install:
  - make deps
install:
  - cd src/c6 && go get -t ./...
  - cd ../..
script:
  - make
  - make test
  - make cover
after_success:
  - make benchcmp
  - goveralls -coverprofile=c6.cov -service=travis-ci
cache:
notifications:
  slack:
    secure: Af6bRpbwtC4794UtB1phbubk63KdethyuMFkk9bxTrEwzTgMN4AdLLv4DYjoeETBhPw3FKc6LurzhsRfNnNT14FaZAW3ZmMTUPxHNKnxu9EvloaizXpwxkKgeVNHneA8gytXZ+s/r/rgP/IkSJcbvbLfpkNvT+lNyPW32jK0CW8=
