---
# travis and modern c++ http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language: c++
git:
  depth: 1
addons:
  apt:
    packages:
    - libgflags-dev
    - libgoogle-glog-dev
    # - gcc-5
    # - g++-5
    # - clang-3.6
os:
- linux
# - osx
compiler:
- clang
- gcc
install:
# - sudo apt-get install libgflags-dev
- sh travis/install.sh
script:
- sh travis/build.sh
- make && make test
cache:
  apt: true
  directories:
  - gtest-1.7.0
  - gflags-2.1.2
# after_success:
# - goveralls -coverprofile=c6.cov -service=travis-ci
# notifications:
#  slack:
#    secure: Af6bRpbwtC4794UtB1phbubk63KdethyuMFkk9bxTrEwzTgMN4AdLLv4DYjoeETBhPw3FKc6LurzhsRfNnNT14FaZAW3ZmMTUPxHNKnxu9EvloaizXpwxkKgeVNHneA8gytXZ+s/r/rgP/IkSJcbvbLfpkNvT+lNyPW32jK0CW8=
