---
# travis and modern c++ http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language: c++
sudo: required
dist: trusty
# see: https://github.com/travis-ci/travis-ci/issues/6120#issuecomment-224072540
# addons:
#   apt:
#     sources:
#     # add PPAs with more up-to-date toolchains
#     - ubuntu-toolchain-r-test
#     - llvm-toolchain-precise-3.6
#     packages:
#     - gcc-5
#     - g++-5
#     - clang-3.6
os:
- linux
# - osx
compiler:
- clang
- gcc
before_install:
- sudo apt-get -qq update
- sudo apt-get -y install libgoogle-glog-dev libgoogle-glog0 libgflags-dev
install:
- sh travis/install.sh
script:
- sh travis/build.sh
- make && make test
cache:
  apt: true
  directories:
  - gtest-1.7.0
  - gflags-2.1.2
# after_success:
# - goveralls -coverprofile=c6.cov -service=travis-ci
# notifications:
#  slack:
#    secure: Af6bRpbwtC4794UtB1phbubk63KdethyuMFkk9bxTrEwzTgMN4AdLLv4DYjoeETBhPw3FKc6LurzhsRfNnNT14FaZAW3ZmMTUPxHNKnxu9EvloaizXpwxkKgeVNHneA8gytXZ+s/r/rgP/IkSJcbvbLfpkNvT+lNyPW32jK0CW8=
