---
# travis and modern c++ http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language: cpp
compiler:
- clang
- gcc
script:
- cmake .
after_success:
# - goveralls -coverprofile=c6.cov -service=travis-ci
notifications:
  slack:
    secure: Af6bRpbwtC4794UtB1phbubk63KdethyuMFkk9bxTrEwzTgMN4AdLLv4DYjoeETBhPw3FKc6LurzhsRfNnNT14FaZAW3ZmMTUPxHNKnxu9EvloaizXpwxkKgeVNHneA8gytXZ+s/r/rgP/IkSJcbvbLfpkNvT+lNyPW32jK0CW8=
