// generated by stringer -type=TokenType; DO NOT EDIT

package c6

import "fmt"

const _TokenType_name = "T_SPACET_COMMENT_LINET_COMMENT_BLOCKT_SEMICOLONT_ID_SELECTORT_CLASS_SELECTORT_TAGNAME_SELECTORT_BRACE_STARTT_BRACE_ENDT_VARIABLET_IMPORTT_CHARSETT_QQ_STRINGT_Q_STRINGT_PAREN_STARTT_PAREN_ENDT_CONSTANTT_DIGITST_PROPERTY_NAMET_PROPERTY_VALUET_HEX_COLORT_COLON"

var _TokenType_index = [...]uint16{0, 7, 21, 36, 47, 60, 76, 94, 107, 118, 128, 136, 145, 156, 166, 179, 190, 200, 208, 223, 239, 250, 257}

func (i TokenType) String() string {
	if i < 0 || i+1 >= TokenType(len(_TokenType_index)) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
