// generated by stringer -type=TokenType; DO NOT EDIT

package c6

import "fmt"

const _TokenType_name = "T_SPACET_COMMENT_LINET_COMMENT_BLOCKT_SEMICOLONT_COMMAT_ID_SELECTORT_CLASS_SELECTORT_TAGNAME_SELECTORT_BRACE_STARTT_BRACE_ENDT_VARIABLET_IMPORTT_CHARSETT_QQ_STRINGT_Q_STRINGT_PAREN_STARTT_PAREN_ENDT_CONSTANTT_INTEGERT_FLOATT_UNIT_PXT_UNIT_PTT_UNIT_EMT_PROPERTY_NAMET_PROPERTY_VALUET_HEX_COLORT_COLON"

var _TokenType_index = [...]uint16{0, 7, 21, 36, 47, 54, 67, 83, 101, 114, 125, 135, 143, 152, 163, 173, 186, 197, 207, 216, 223, 232, 241, 250, 265, 281, 292, 299}

func (i TokenType) String() string {
	if i < 0 || i+1 >= TokenType(len(_TokenType_index)) {
		return fmt.Sprintf("TokenType(%d)", i)
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
